/*
 Generated by typeshare 1.13.2
*/

export interface Vault {
	id: string;
	name: string;
	filepath: string;
}

export interface Config {
	vaults: Vault[];
}

export interface PackageInfoSerializable {
	name: string;
	version: string;
	authors: string;
	description: string;
}

